force-app/main/default/objects/System_Notification__e/System_Notification__e.object-meta.xml
<CustomObject>
    <description>Event used to notify system events for the app such as errors or important alerts</description>
    <label>System Notification</label>
    <pluralLabel>System Notifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/System_Notification__e/fields/Error_Type__c.field-meta.xml
<CustomField>
    <fullName>Error_Type__c</fullName>
    <description>Error type can be Error, Notification or Warning</description>
    <label>Error Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Notification__e/fields/Identification__c.field-meta.xml
<CustomField>
    <fullName>Identification__c</fullName>
    <description>Id of the record or error Id</description>
    <label>Identification</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Notification__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Text message from error or exception to save publish in the event</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PublishNotificationEX.cls
/**
 * Utility helper calss to publish notification events
 * Author: A.I.
 */
public class PublishNotificationEX {

    // Example to publish
    // PublishNotificationEX.publishError('Error on execution', '01iqw78iwu87w', 'error'); info
    // PublishNotificationEX.publishError('Missing Data', '01iqw78iwu87w', 'warning');
    public static void publishError(String msg, String id, String errType){
        // Publish messages as notifications
        List<System_Notification__e> notifications = new List<System_Notification__e>();
        notifications.add(new System_Notification__e(Message__c = msg, Identification__c = id, Error_Type__c = errType));

        List<Database.SaveResult> results = EventBus.publish(notifications);
        // Inspect publishing results
        for (Database.SaveResult result : results) {
            if (!result.isSuccess()) {
                for (Database.Error error : result.getErrors()) {
                    System.debug('Error returned: ' + error.getStatusCode() +' - '+ error.getMessage());
                }
            }
        }
    }

}